### ISSUE TITLE
alf-core:jar dependency not accessible outsite uniroma3 repository

### ISSUE THREAD

**Issue by DrSnowbird** [dice-group/REX#1]
Error: --- (run 'mvn  install')
[ERROR] Failed to execute goal on project REX: Could not resolve dependencies for project org.aksw:REX:jar:1.0: Failed to collect dependencies at it.uniroma3.dia.db:alf-core:jar:0.0.17-SNAPSHOT: Failed to read artifact descriptor for it.uniroma3.dia.db:alf-core:jar:0.0.17-SNAPSHOT: Could not transfer artifact it.uniroma3.dia.db:alf-core:pom:0.0.17-SNAPSHOT from/to alfred-snapshots (http://ortles.dia.uniroma3.it:8888/nexus/content/repositories/snapshots): Connect to ortles.dia.uniroma3.it:8888 [ortles.dia.uniroma3.it/193.204.161.215] failed: Connection refused -> [Help 1]

**Comment by RicardoUsbeck** [comment]
Hi!
We added the missing dependency to our maven at aksw.org 

http://maven.aksw.org/archiva/#artifact/it.uniroma3.dia.db/alf-core/0.0.17-SNAPSHOT

**Comment by MichaelRoeder** [comment]
an additional hint:
You can access the maven repo with adding the following snippet to your pom file:

```
    <repositories>
        <repository>
            <id>maven.aksw.snapshots</id>
            <name>University Leipzig, AKSW Maven2 Repository</name>
            <url>http://maven.aksw.org/repository/snapshots</url>
        </repository>
    </repositories>
```

Please close this issue if your problem has been fixed that way. Otherwise, let us know.

**Comment by DrSnowbird** [comment]
Hi, 
Thanks for updating in release-v1.0.0 by new repo in "http://maven.aksw.org/repository/snapshots".
It did solve the alf-core not found issue. But, new errors now failed at missing 

```
"it.uniroma3.dia.dom.visitor.DOMVisitorListener" and
"it.uniroma3.dia.dom.visitor.DOMVisitorListenerAdapter"
```

I manually look up the repo web site and there is no "it.uniroma3.dia.dom" aritifact there, please go to the url below to see what I saw:
http://maven.aksw.org/archiva/#browse/it.uniroma3.dia

Thanks in advance.
- Ray

### --- GIT Branch info ---

```
user1@lion12:~/Tools/AKSW/REX$ git branch -a
* release-v1.0.0
  remotes/origin/HEAD -> origin/release-v1.0.0
  remotes/origin/gh-pages
  remotes/origin/master
  remotes/origin/release-v1.0.0

user1@lion12:~/Tools/AKSW/REX$ mvn clean compile assembly:single | tee build.log
```

### --- Build Failure ---

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.245 s
[INFO] Finished at: 2016-05-20T17:35:08-04:00
[INFO] Final Memory: 34M/315M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project REX: Compilation failure: Compilation failure:
[ERROR] /home/user1/Tools/AKSW/REX/src/main/java/org/aksw/rex/xpath/alfred/ALFREDPageRetrieval.java:[141,54] cannot access it.uniroma3.dia.dom.visitor.DOMVisitorListener
[ERROR] class file for it.uniroma3.dia.dom.visitor.DOMVisitorListener not found
[ERROR] /home/user1/Tools/AKSW/REX/src/main/java/org/aksw/rex/xpath/alfred/ALFREDPageRetrieval.java:[141,100] cannot access it.uniroma3.dia.dom.visitor.DOMVisitorListenerAdapter
[ERROR] class file for it.uniroma3.dia.dom.visitor.DOMVisitorListenerAdapter not found

```

**Comment by MichaelRoeder** [comment]
Hi,

sorry, there was a mistake in our deployment of the missing jar file. Please try it again. Note, that you might have to add a `-U` to your `mvn` command to force the update of the SNAPSHOT dependencies.

Cheers,
Micha

**Comment by DrSnowbird** [comment]
Hi Micha,
Thanks for responding and updating repo for depdencies.
Yes, now the "mvn -U ..." has built successfully.
Very cheerfully to all, Thanks much again.
- Ray
